title: "Tippani Hemanth — BA & Consulting Portfolio"
description: "Business Analyst portfolio (Unexia, Synpulse, Deloitte, Scottish Water + dissertation)"
theme: jekyll-theme-cayman
markdown: kramdown
